export enum ActionTypes {
  PURGE,
  OPEN_WINDOW,
  SET_CURRENT_PROJECT,
  SET_PATTERNS,
  SET_RECORDING_MELODY,
  SET_CURRENT_KEYS,
  UPDATE_CURRENT_PROJECT,
  SET_WINDOWS,
  SET_CURRENT_SYNTH,
  SET_MELODIES,
  SET_PATTERN_PLAYERS,

  SET_IS_RECORDING_MELODY,
  SET_INSTRUMENTS,

  SET_TIMED_MELODIES,
  SET_SELECTED_TIMED_MELODY_ID,
  SET_SELECTED_MELODY_ID,
  SET_SELECTED_PATTERN_ID,
  SET_SELECTED_INSTRUMENT_ID,
}
